apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: checkout-scaledobject
spec:
  scaleTargetRef:
    name: checkout
  minReplicaCount: 1
  maxReplicaCount: 3
  cooldownPeriod: 30
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "10"