apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: checkout-http
spec:
  scaleTargetRef:
    name: checkout
    service: checkout
    port: 80
  replicas:
    min: 0
    max: 5
  scaledownPeriod: 30
  targetPendingRequests: 1