apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: checkout-scaledobject
spec:
  hosts:
    - "*"
  pathPrefixes:
    - /api/checkout
  scaleTargetRef:
    name: checkout
    service: checkout
    port: 80
  replicas:
    min: 0
    max: 5